/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubscriptionIndexRouteImport } from './routes/_app/subscription/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRulesIndexRouteImport } from './routes/_app/rules/index'
import { Route as AppLogsIndexRouteImport } from './routes/_app/logs/index'
import { Route as AppForwardingIndexRouteImport } from './routes/_app/forwarding/index'

const SigninLazyRouteImport = createFileRoute('/signin')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionIndexRoute = AppSubscriptionIndexRouteImport.update({
  id: '/subscription/',
  path: '/subscription/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesIndexRoute = AppRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppForwardingIndexRoute = AppForwardingIndexRouteImport.update({
  id: '/forwarding/',
  path: '/forwarding/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/forwarding': typeof AppForwardingIndexRoute
  '/logs': typeof AppLogsIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/subscription': typeof AppSubscriptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/forwarding': typeof AppForwardingIndexRoute
  '/logs': typeof AppLogsIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/subscription': typeof AppSubscriptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/forwarding/': typeof AppForwardingIndexRoute
  '/_app/logs/': typeof AppLogsIndexRoute
  '/_app/rules/': typeof AppRulesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/subscription/': typeof AppSubscriptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/forwarding'
    | '/logs'
    | '/rules'
    | '/settings'
    | '/subscription'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/forwarding'
    | '/logs'
    | '/rules'
    | '/settings'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/_app/forwarding/'
    | '/_app/logs/'
    | '/_app/rules/'
    | '/_app/settings/'
    | '/_app/subscription/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subscription/': {
      id: '/_app/subscription/'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules/': {
      id: '/_app/rules/'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/': {
      id: '/_app/logs/'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forwarding/': {
      id: '/_app/forwarding/'
      path: '/forwarding'
      fullPath: '/forwarding'
      preLoaderRoute: typeof AppForwardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppForwardingIndexRoute: typeof AppForwardingIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppRulesIndexRoute: typeof AppRulesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSubscriptionIndexRoute: typeof AppSubscriptionIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppForwardingIndexRoute: AppForwardingIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppRulesIndexRoute: AppRulesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSubscriptionIndexRoute: AppSubscriptionIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
