/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppGroupsIndexRouteImport } from './routes/_app/groups/index'
import { Route as AppBookmarksIndexRouteImport } from './routes/_app/bookmarks/index'
import { Route as AppAddIndexRouteImport } from './routes/_app/add/index'

const SigninLazyRouteImport = createFileRoute('/signin')()

const SigninLazyRoute = SigninLazyRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signin.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsIndexRoute = AppGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksIndexRoute = AppBookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddIndexRoute = AppAddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/add': typeof AppAddIndexRoute
  '/bookmarks': typeof AppBookmarksIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninLazyRoute
  '/add': typeof AppAddIndexRoute
  '/bookmarks': typeof AppBookmarksIndexRoute
  '/groups': typeof AppGroupsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninLazyRoute
  '/_app/add/': typeof AppAddIndexRoute
  '/_app/bookmarks/': typeof AppBookmarksIndexRoute
  '/_app/groups/': typeof AppGroupsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/add' | '/bookmarks' | '/groups' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/add' | '/bookmarks' | '/groups' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/_app/add/'
    | '/_app/bookmarks/'
    | '/_app/groups/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninLazyRoute: typeof SigninLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups/': {
      id: '/_app/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks/': {
      id: '/_app/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add/': {
      id: '/_app/add/'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddIndexRoute: typeof AppAddIndexRoute
  AppBookmarksIndexRoute: typeof AppBookmarksIndexRoute
  AppGroupsIndexRoute: typeof AppGroupsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddIndexRoute: AppAddIndexRoute,
  AppBookmarksIndexRoute: AppBookmarksIndexRoute,
  AppGroupsIndexRoute: AppGroupsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninLazyRoute: SigninLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
